services:
  discamb-matts:
    image: "qcrbox/discamb-matts:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}"
    environment:
      QCRBOX_APPLICATION_DISPLAY_NAME: "DiscambMATTS"
      QCRBOX__NATS__HOST: "qcrbox-nats"
      QCRBOX__REGISTRY__SERVER__HOST: "qcrbox-registry"
      QCRBOX__REGISTRY__SERVER__PORT: "8000"
    depends_on:
      qcrbox-registry:
        condition: service_healthy
    networks:
      - qcrbox-net
    restart: unless-stopped
    logging:
      driver: "syslog"
      options:
        syslog-address: udp://127.0.0.1:514
        tag: discamb-matts