repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.2.2
    hooks:
      # Run the ruff linter.
      - id: ruff
        args: [ --fix, --config, pyqcrbox/pyproject.toml ]
      # Run the ruff formatter.
      - id: ruff-format
        args: [ --config, pyqcrbox/pyproject.toml ]
      # Check import contracts
  - repo: https://github.com/seddonym/import-linter
    rev: v2.0
    hooks:
      - id: import-linter
