version: "3.8"

services:
  qcrbox-message-bus:
    image: "qcrbox/message-bus:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}"
    build:
      context: services/core/QCRBOX_message_bus/
    networks:
      - qcrbox-net
    hostname: "qcrbox-message-bus"
    ports:
      - "${QCRBOX_BIND_ADDRESS:?Must set env var QCRBOX_BIND_ADDRESS}:${QCRBOX_PORT_RABBITMQ:?Must set env var QCRBOX_PORT_RABBITMQ}:5672"
      - "${QCRBOX_BIND_ADDRESS:?Must set env var QCRBOX_BIND_ADDRESS}:${QCRBOX_PORT_RABBITMQ_MANAGEMENT:?Must set env var QCRBOX_PORT_RABBITMQ_MANAGEMENT}:15672"
      - "${QCRBOX_BIND_ADDRESS:?Must set env var QCRBOX_BIND_ADDRESS}:${QCRBOX_PORT_WEBSOCKET:?Must set env var QCRBOX_PORT_WEBSOCKET}:4000"
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q is_running
      interval: 5s
      timeout: 30s
      start_period: 30s
      # Note: the 'start_interval' option is not supported yet
      # (see https://github.com/docker/compose/issues/10830#issuecomment-1722514100)
      #start_interval: 1s
      retries: 5

networks:
  qcrbox-net:
