services:
  base-ancestor:
    image: "qcrbox/base-ancestor:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}"
    build:
      context: services/base_images/base_ancestor/
      args:
        QCRBOX_ROOT_DIR: ${QCRBOX_ROOT_DIR:?Must set env var QCRBOX_ROOT_DIR}
        QCRBOX_VOLUMES_ROOT_DIR: ${QCRBOX_VOLUMES_ROOT_DIR:?Must set env var QCRBOX_VOLUMES_ROOT_DIR}
        QCRBOX_SUPERVISORD_CONF_DIR: ${QCRBOX_SUPERVISORD_CONF_DIR:?Must set env var QCRBOX_SUPERVISORD_CONF_DIR}
        QCRBOX__RABBITMQ__HOST: "qcrbox-message-bus"
        QCRBOX__RABBITMQ__PORT: "5672"
        PYQCRBOX_PYTHON_PACKAGE_VERSION: ${PYQCRBOX_PYTHON_PACKAGE_VERSION:-${QCRBOX_DOCKER_TAG}}
        QCRBOX_PYTHON_PACKAGE_VERSION: ${QCRBOX_PYTHON_PACKAGE_VERSION:-${QCRBOX_DOCKER_TAG}}
        QCRBOXTOOLS_VERSION: ${QCRBOXTOOLS_VERSION:?Must set env var QCRBOXTOOLS_VERSION}

  base-application:
    image: "qcrbox/base-application:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}"
    build:
      context: services/base_images/base_application/
      args:
        QCRBOX_DOCKER_TAG: ${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}
        QCRBOX_ROOT_DIR: ${QCRBOX_ROOT_DIR:?Must set env var QCRBOX_ROOT_DIR}
        QCRBOX_SUPERVISORD_CONF_DIR: ${QCRBOX_SUPERVISORD_CONF_DIR:?Must set env var QCRBOX_SUPERVISORD_CONF_DIR}
        QCRBOX_REGISTRY_HOST: "qcrbox-registry"
        QCRBOX_REGISTRY_PORT: "8000"

  base-novnc:
    image: "qcrbox/base-novnc:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}"
    build:
      context: services/base_images/base_novnc/
      args:
        QCRBOX_DOCKER_TAG: ${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}
        QCRBOX_ROOT_DIR: ${QCRBOX_ROOT_DIR:?Must set env var QCRBOX_ROOT_DIR}
        QCRBOX_SUPERVISORD_CONF_DIR: ${QCRBOX_SUPERVISORD_CONF_DIR:?Must set env var QCRBOX_SUPERVISORD_CONF_DIR}

  base-wine:
    image: "qcrbox/base-wine:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}"
    build:
      context: services/base_images/base_wine/
      args:
        QCRBOX_DOCKER_TAG: ${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}
        QCRBOX_WINE_INSTALLATIONS_DIR: ${QCRBOX_WINE_INSTALLATIONS_DIR:?Must set env var QCRBOX_WINE_INSTALLATIONS_DIR}
        QCRBOX_SHARED_FILES_DIR_CONTAINER_PATH: ${QCRBOX_SHARED_FILES_DIR_CONTAINER_PATH:?Must set env var QCRBOX_SHARED_FILES_DIR_CONTAINER_PATH}
        # We set a default value for QCRBOX_WINEARCH just so that we can run the base-wine container for debugging,
        # but this must be set by each application as required.
        QCRBOX_WINEARCH: ${QCRBOX_WINEARCH:-win32}
    #depends_on:
    #  - base-novnc
    #environment:
    #  QCRBOX_APP_DISPLAY_NAME: "QCrBox-Wine"
    #  QCRBOX_RABBITMQ_QUEUE_NAME: "qcrbox-base-wine"
    #volumes:
    #  - wine_installations_dir:${QCRBOX_WINE_INSTALLATIONS_DIR:?Must set env var QCRBOX_WINE_INSTALLATIONS_DIR}
    #networks:
    #  - qcrbox-net
    #ports:
    #  - "${QCRBOX_BIND_ADDRESS}:${QCRBOX_PORT_BASE_IMAGE_WINE:?Must set env var QCRBOX_PORT_BASE_IMAGE_WINE}:8080"
    #restart: "unless-stopped"

  qcrbox-message-bus:
    build:
      context: services/core/qcrbox_message_bus/

  qcrbox-registry:
    build:
      context: services/core/qcrbox_registry
      args:
        QCRBOX_DOCKER_TAG: ${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}
        QCRBOX_ROOT_DIR: ${QCRBOX_ROOT_DIR:?Must set env var QCRBOX_ROOT_DIR}
        QCRBOX_SUPERVISORD_CONF_DIR: ${QCRBOX_SUPERVISORD_CONF_DIR:?Must set env var QCRBOX_SUPERVISORD_CONF_DIR}
        QCRBOX_REGISTRY_DB_DIR: ${QCRBOX_REGISTRY_DB_DIR:?Must set env var QCRBOX_REGISTRY_DB_DIR}

  qcrbox-nextflow:
    build:
      context: services/core/qcrbox_nextflow
      args:
        QCRBOX_DOCKER_TAG: ${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}
        QCRBOX_ROOT_DIR: ${QCRBOX_ROOT_DIR:?Must set env var QCRBOX_ROOT_DIR}
        QCRBOX_SUPERVISORD_CONF_DIR: ${QCRBOX_SUPERVISORD_CONF_DIR:?Must set env var QCRBOX_SUPERVISORD_CONF_DIR}
        PYQCRBOX_PYTHON_PACKAGE_VERSION: ${PYQCRBOX_PYTHON_PACKAGE_VERSION:-${QCRBOX_DOCKER_TAG}}
        QCRBOX_PYTHON_PACKAGE_VERSION: ${QCRBOX_PYTHON_PACKAGE_VERSION:-${QCRBOX_DOCKER_TAG}}
        QCRBOXTOOLS_VERSION: ${QCRBOXTOOLS_VERSION:?Must set env var QCRBOXTOOLS_VERSION}
        QCRBOX_NEXTFLOW_HOME: "${QCRBOX_NEXTFLOW_HOME:?Must set env var QCRBOX_NEXTFLOW_HOME}"
        NEXTFLOW_VERSION: "23.10.0"
