version: "3.8"

services:
  qcrbox-message-bus:
    image: "qcrbox/message-bus:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}"
    volumes:
      - qcrbox-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - qcrbox-net
    hostname: "qcrbox-message-bus"
    ports:
      - "${QCRBOX_BIND_ADDRESS:?Must set env var QCRBOX_BIND_ADDRESS}:${QCRBOX_RABBITMQ_PORT:?Must set env var QCRBOX_RABBITMQ_PORT}:5672"
      - "${QCRBOX_BIND_ADDRESS:?Must set env var QCRBOX_BIND_ADDRESS}:${QCRBOX_RABBITMQ_MANAGEMENT_PORT:?Must set env var QCRBOX_RABBITMQ_MANAGEMENT_PORT}:15672"
#      - "${QCRBOX_BIND_ADDRESS:?Must set env var QCRBOX_BIND_ADDRESS}:${QCRBOX_PORT_WEBSOCKET:?Must set env var QCRBOX_PORT_WEBSOCKET}:4000"
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q is_running
      interval: 5s
      timeout: 30s
      start_period: 30s
      # Note: the 'start_interval' option is not supported yet
      # (see https://github.com/docker/compose/issues/10830#issuecomment-1722514100)
      #start_interval: 1s
      retries: 5

  qcrbox-registry:
    image: "qcrbox/registry:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}"
    volumes:
      - ./shared_files:${QCRBOX_SHARED_FILES_DIR:?Must set env var QCRBOX_SHARED_FILES_DIR}
      - qcrbox-registry-db:${QCRBOX_REGISTRY_DB_DIR:?Must set env var QCRBOX_REGISTRY_DB_DIR}
    ports:
      - "${QCRBOX_BIND_ADDRESS}:${QCRBOX_REGISTRY_PORT:?Must set env var QCRBOX_REGISTRY_PORT}:8000"
    depends_on:
      qcrbox-message-bus:
        condition: service_healthy
    environment:
      QCRBOX_RABBITMQ_QUEUE_NAME: "qcrbox_registry"
      QCRBOX_REGISTRY_DB_DIR: "${QCRBOX_REGISTRY_DB_DIR:?Must set env var QCRBOX_REGISTRY_DB_DIR}"
    networks:
      - qcrbox-net
    restart: "unless-stopped"

  qcrbox-nextflow:
    image: "qcrbox/nextflow:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - qcrbox-nextflow-home:${QCRBOX_NEXTFLOW_HOME:?Must set env var QCRBOX_NEXTFLOW_HOME}
      - ./shared_files:${QCRBOX_SHARED_FILES_DIR:?Must set env var QCRBOX_SHARED_FILES_DIR}
      # Note: the env var QCRBOX_SHARED_FILES_DIR_HOST_PATH is required byt will be set automatically by
      # the `qcb` command line tool when `qcb up qcrbox-nextflow` is invoked.
      - ./shared_files:${QCRBOX_SHARED_FILES_DIR_HOST_PATH:?Must set env var QCRBOX_SHARED_FILES_DIR_HOST_PATH}
    depends_on:
      qcrbox-message-bus:
        condition: service_healthy
    environment:
      QCRBOX_RABBITMQ_QUEUE_NAME: "qcrbox_nextflow"
      QCRBOX_REGISTRY_HOST: "qcrbox-registry"
      QCRBOX_REGISTRY_PORT: "8000"
      QCRBOX_NEXTFLOW_HOME: "${QCRBOX_NEXTFLOW_HOME:?Must set env var QCRBOX_NEXTFLOW_HOME}"
    networks:
      - qcrbox-net
    restart: "unless-stopped"

  shelx:
    image: "qcrbox/shelx:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}"
    build:
      context: services/applications/shelx
      args:
        QCRBOX_DOCKER_TAG: ${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}
    environment:
      QCRBOX_RABBITMQ_QUEUE_NAME: "shelx"
      QCRBOX_REGISTRY_HOST: "qcrbox-registry"
      QCRBOX_REGISTRY_PORT: "8000"
    volumes:
      - ./shared_files:${QCRBOX_SHARED_FILES_DIR:?Must set env var QCRBOX_SHARED_FILES_DIR}
    depends_on:
      qcrbox-registry:
        condition: service_healthy
    networks:
      - qcrbox-net
    restart: unless-stopped

  crystal-explorer:
    image: "qcrbox/crystal-explorer:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}"
    volumes:
      - ./shared_files:${QCRBOX_SHARED_FILES_DIR:?Must set env var QCRBOX_SHARED_FILES_DIR}
    networks:
      - qcrbox-net
    ports:
      - "${QCRBOX_BIND_ADDRESS}:${QCRBOX_CRYSTAL_EXPLORER_PORT:?Must set env var QCRBOX_CRYSTAL_EXPLORER_PORT}:8080"
    depends_on:
      - qcrbox-registry
    restart: unless-stopped
    environment:
      QCRBOX_APPLICATION_DISPLAY_NAME: "CrystalExplorer"
      QCRBOX_RABBITMQ_QUEUE_NAME: "crystal-explorer"
      QCRBOX_REGISTRY_HOST: "qcrbox-registry"
      QCRBOX_REGISTRY_PORT: "8000"

  olex2-linux:
    image: qcrbox/olex2-linux:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}
    volumes:
      - ./shared_files:${QCRBOX_SHARED_FILES_DIR:?Must set env var QCRBOX_SHARED_FILES_DIR}
    networks:
      - qcrbox-net
    ports:
      - "${QCRBOX_BIND_ADDRESS}:${QCRBOX_OLEX2_LINUX_PORT:?Must set env var QCRBOX_OLEX2_LINUX_PORT}:8080"
    depends_on:
      - qcrbox-registry
    restart: unless-stopped
    environment:
      QCRBOX_APPLICATION_DISPLAY_NAME: "Olex2"
      QCRBOX_RABBITMQ_QUEUE_NAME: "olex2"
      QCRBOX_REGISTRY_HOST: "qcrbox-registry"
      QCRBOX_REGISTRY_PORT: "8000"

networks:
  qcrbox-net:

volumes:
  qcrbox-rabbitmq-data:
  qcrbox-registry-db:
  qcrbox-nextflow-home:
