site_name: Quantum Crystallography Toolbox (QCrBox)
site_url: https://qcrbox.github.io/QCrBox/
site_dir: .build/docs_site
theme:
  name: "material"
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    #- navigation.tracking
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: "deep purple"
    accent: "purple"
  logo: "images/logo_white.png"
  favicon: "images/logo_black.png"
extra_css:
  - qcrbox_custom_styling.css

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: false
  - mkdocs-jupyter:
      ignore: ["tutorials/example_support/*"]
      ignore_h1_titles: True
  - markdown-exec:
      ansi: required

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: "#"

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
#  - pymdownx.emoji:
#      emoji_index: !!python/name:materialx.emoji.twemoji
#      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
