services:
  mopro:
    image: "qcrbox/mopro:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}"
    volumes:
      - ${QCRBOX_SHARED_FILES_DIR_HOST_PATH:?Must set env var QCRBOX_SHARED_FILES_DIR_HOST_PATH}:${QCRBOX_SHARED_FILES_DIR_CONTAINER_PATH:?Must set env var QCRBOX_SHARED_FILES_DIR_CONTAINER_PATH}
    networks:
      - qcrbox-net
    ports:
      - "${QCRBOX_BIND_ADDRESS}:${QCRBOX_MOPRO_PORT:?Must set env var QCRBOX_MOPRO_PORT}:8080"
    depends_on:
      qcrbox-registry:
        condition: service_healthy
    restart: unless-stopped
    environment:
      QCRBOX_APPLICATION_DISPLAY_NAME: "MoPro"
      QCRBOX__NATS__HOST: "qcrbox-nats"
      QCRBOX__REGISTRY__SERVER__HOST: "qcrbox-registry"
      QCRBOX__REGISTRY__SERVER__PORT: "8000"
    labels:
      traefik.enable: true
      traefik.http.routers.to-mopro-path-prefix.rule: Path(`/gui/mopro`)
      traefik.http.routers.to-mopro-path-prefix.middlewares: redirect-gui-mopro-path
      traefik.http.routers.to-mopro-path-prefix.service: mopro-service
      traefik.http.middlewares.redirect-gui-mopro-path.redirectregex.regex: ^http://(.+)/gui/mopro(/?)$$
      traefik.http.middlewares.redirect-gui-mopro-path.redirectregex.replacement: http://mopro.gui.$$1/vnc.html?path=vnc&autoconnect=true&resize=remote&reconnect=true&show_dot=true

      traefik.http.routers.to-mopro-subdomain.rule: HostRegexp(`^mopro\.gui\..+$$`)
      traefik.http.routers.to-mopro-subdomain.middlewares: redirect-gui-mopro-subdomain
      traefik.http.routers.to-mopro-subdomain.service: mopro-service
      traefik.http.middlewares.redirect-gui-mopro-subdomain.redirectregex.regex: ^http://mopro\.gui\.([^/]+)(/?)$$
      traefik.http.middlewares.redirect-gui-mopro-subdomain.redirectregex.replacement: http://mopro.gui.$$1/vnc.html?path=vnc&autoconnect=true&resize=remote&reconnect=true&show_dot=true

      traefik.http.services.mopro-service.loadbalancer.server.scheme: http
      traefik.http.services.mopro-service.loadbalancer.server.port: 8080
