services:
  mopro:
    image: "qcrbox/mopro:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}"
    build:
      context: services/applications/mopro/
      args:
        QCRBOX_DOCKER_TAG: ${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}
    environment:
      QCRBOX_APPLICATION_DISPLAY_NAME: "MoProSuite"
      QCRBOX_REGISTRY_HOST: "qcrbox-registry"
      QCRBOX_REGISTRY_PORT: "8000"
    ports:
      - "${QCRBOX_BIND_ADDRESS}:${QCRBOX_MOPRO_PORT:?Must set env var QCRBOX_MOPRO_PORT}:8080"
    volumes:
      - ${QCRBOX_SHARED_FILES_DIR_HOST_PATH:?Must set env var QCRBOX_SHARED_FILES_DIR_HOST_PATH}:${QCRBOX_SHARED_FILES_DIR_CONTAINER_PATH:?Must set env var QCRBOX_SHARED_FILES_DIR_CONTAINER_PATH}
    depends_on:
      qcrbox-registry:
        condition: service_healthy
    networks:
      - qcrbox-net
    restart: unless-stopped
