#
# Configuration for the application 'dummy_cli'
#
name: Dummy CLI
slug: dummy_cli
version: "0.1.0"
description: Dummy non-interactive application for development, testing and debugging
url: ""

commands:
  - name: greet_and_sleep
    description: Print a greeting message, then wait for a given duration before returning.
    implemented_as: python_callable
    import_path: pyqcrbox.helpers
    parameters:
      - name: name
        dtype: str
        description: The name of the person to be greeted
      - name: duration
        dtype: float
        description: Sleep duration (in seconds)
        default_value: 5.0
        valid_value:
          numeric_range: [0, 10]

  - name: print_cif
    description: A short Python function which prints the name of the input CIF and returns it back
    implemented_as: python_callable
    import_path: sample_functions
    parameters:
      - name: input_cif
        dtype: QCrBox.cif_data_file
        description: The input CIF file
      - name: print_times
        dtype: int
        description: The number of times to print the CIF file
        default_value: 2
        valid_value:
          numeric_range: [1, 10]

  - name: infinite_loop
    description: A Python function which loops infinitely until cancelled
    implemented_as: python_callable
    import_path: sample_functions
    parameters:
      - name: dummy
        dtype: str
        description: An unused dummy parameter

  - name: change_cif_name
    description: A Python function which changes the file name of a CIF
    implemented_as: python_callable
    import_path: sample_functions
    parameters:
      - name: input_cif
        dtype: QCrBox.cif_data_file
        description: The main CIF
        required_entry_sets: [ "cell_elements" ]
      - name: output_cif_name
        dtype: QCrBox.output_cif
        description: The name of the output CIF file
        required_entries: [
          "_atom_site_label", "_atom_site_fract_x", "_atom_site_fract_y", "_atom_site_fract_z",
          "_atom_site_occupancy", "_atom_site_U_iso_or_equiv", "_atom_site_type_symbol",
          one_of: ["_symmetry_equiv_pos_as_xyz", "_space_group_symop_operation_xyz"]
        ]
        optional_entries: [
          "_atom_site_aniso_label", "_atom_site_aniso_U_11", "_atom_site_aniso_U_22",
          "_atom_site_aniso_U_33", "_atom_site_aniso_U_12", "_atom_site_aniso_U_13",
          "_atom_site_aniso_U_23", "_atom_site_adp_type", "_atom_site_site_symmetry_order",
          "_atom_site_calc_flag", "_atom_site_refinement_flags_posn", "_atom_site_refinement_flags_adp"
        ]
        invalidated_entries: [
          "_atom_site.*", "_geom.*", ".*refine.*", "_iucr.*", "_shelx.*"
        ]

  - name: print_two_cif
    description: A Python function which prints the contents of two CIF files
    implemented_as: python_callable
    import_path: sample_functions
    parameters:
      - name: cif1
        dtype: QCrBox.cif_data_file
        description: The first CIF file
      # Note that we can only have ONE cif_data_file, other CIFs have to be data_files
      - name: cif2
        dtype: QCrBox.data_file
        description: The second CIF file

  - name: test_cif_to_specific
    description: A Python function which is used to test that the cif to specific format transformation works
    implemented_as: python_callable
    import_path: sample_functions
    parameters:
      - name: "input_cif"
        dtype: "QCrBox.cif_data_file"
        merge_su: Yes
        custom_categories: [test_value, test_loop]
        required_entry_sets: [input_test1]
        optional_entry_sets: [input_test2]
        required_entries: [one_of: [_cell_length_b, _invalid_cif_value]]
        optional_entries: [_atom_site_label]
      - name: "output_cif_dummy"
        dtype: "QCrBox.output_cif"

  - name: test_to_unified_cif
    description: A Python function which is used to test that a cif can be returned as a unified cif
    implemented_as: python_callable
    import_path: sample_functions
    parameters :
      - name: "input_cif"
        dtype: "QCrBox.cif_data_file"
        merge_su: Yes
        custom_categories: [test_value, test_loop]
        required_entry_sets: [input_test1]
        optional_entry_sets: [input_test2]
        required_entries: [one_of: [_cell_length_b, _invalid_cif_value]]
        optional_entries: [_atom_site_label]
      - name: "to_merge_cif"
        dtype: QCrBox.data_file
      - name: "output_cif"
        dtype: "QCrBox.output_cif"
        custom_categories: [test_value, test_loop]
        required_entry_sets: [output_test]
        required_entries: [_test_loop_value_without_su]
        optional_entries: [_nonexistent_keyword]
        invalidated_entries: [_test_value_invalidated, _test_loop_value_invalidated]

  - name: test_merged_cifs
    description: A Python function which is used to test that cifs can be "simple" merged together
    implemented_as: python_callable
    import_path: sample_functions
    parameters :
      - name: "input_cif"
        dtype: "QCrBox.cif_data_file"
      - name: "output_cif"
        dtype: "QCrBox.output_cif"

cif_entry_sets:
  - name: "cell_elements"
    required: [
      "_cell_length_a", "_cell_length_b", "_cell_length_c", "_cell_angle_alpha",
      "_cell_angle_beta", "_cell_angle_gamma", "_chemical_formula_sum"
    ]
  - name: input_test1
    required : [ _cell_length_a ]
    optional : [ _atom_site_fract_y ]
  - name: input_test2
    required : [ _invalid_keyword, _atom_site_fract_x ]
  - name: output_test
    required : [ _test_value_with_su ]
    optional : [ _test_loop_id ]

qcrbox_yaml_spec_version: "0.1"
