services:
  dummy_cli:
    image: "qcrbox/dummy_cli:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}"
    build:
      context: services/applications/dummy_cli/
      args:
        QCRBOX_DOCKER_TAG: ${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}
    depends_on:
      qcrbox-registry:
        condition: service_healthy
    volumes:
      - ${QCRBOX_SHARED_FILES_DIR_HOST_PATH:?Must set env var QCRBOX_SHARED_FILES_DIR_HOST_PATH}:${QCRBOX_SHARED_FILES_DIR_CONTAINER_PATH:?Must set env var QCRBOX_SHARED_FILES_DIR_CONTAINER_PATH}
    networks:
      - qcrbox-net
    restart: unless-stopped
