#
# Configuration for the application 'qcrbox_quality'
#
name: "Qcrbox Quality"
slug: "qcrbox_quality"
version: "x.y.z"
description: "Brief description of the application."
url: ""

commands:
  - name: "basic_model_quality_indicators"
    description: "create boxes for some quality indicators"
    implemented_as: "python_callable"
    import_path: "qcrbox_quality_module"
    parameters:
      - name: "input_cif_path"
        dtype: "QCrBox.input_cif"
        required_entries: [
          "_refine_ls.r_factor_all",
          "_refine_ls.wr_factor_gt",
          "_refine.diff_density_max",
          "_refine.diff_density_min",
          "_refine_ls.d_res_high",
          "_refine_ls.goodness_of_fit_ref"
        ]
      - name: "output_html_path"
        dtype: str
        default_value: 5.0
        description: "Sleep duration (in seconds)"

qcrbox_yaml_spec_version: "0.1"
