services:
  qcrbox_quality:
    image: "qcrbox/qcrbox_quality:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}"

    depends_on:
      qcrbox-registry:
        condition: service_healthy
    volumes:
      - ${QCRBOX_SHARED_FILES_DIR_HOST_PATH:?Must set env var QCRBOX_SHARED_FILES_DIR_HOST_PATH}:${QCRBOX_SHARED_FILES_DIR_CONTAINER_PATH:?Must set env var QCRBOX_SHARED_FILES_DIR_CONTAINER_PATH}
    networks:
      - qcrbox-net
    restart: unless-stopped
    environment:
      QCRBOX_APPLICATION_DISPLAY_NAME: "Quality Display"
      QCRBOX__NATS__HOST: "qcrbox-nats"
      QCRBOX__REGISTRY__SERVER__PORT: "8000"
      ALLOWED_HOSTS: "*"
    labels:
      traefik.enable: true
      traefik.http.routers.to-qcrbox-quality-path-prefix.rule: PathPrefix(`/gui/qcrbox_quality`)
      traefik.http.routers.to-qcrbox-quality-path-prefix.middlewares: strip-qcrbox-quality-prefix
      traefik.http.routers.to-qcrbox-quality-path-prefix.service: qcrbox_quality-service
      traefik.http.middlewares.strip-qcrbox-quality-prefix.stripprefix.prefixes: /gui/qcrbox_quality

      traefik.http.routers.to-qcrbox-quality-subdomain.rule: HostRegexp(`^qcrbox-quality\.gui\..+$$`)
      traefik.http.routers.to-qcrbox-quality-subdomain.service: qcrbox_quality-service

      traefik.http.services.qcrbox_quality-service.loadbalancer.server.scheme: http
      traefik.http.services.qcrbox_quality-service.loadbalancer.server.port: 8080
    logging:
      driver: "syslog"
      options:
        syslog-address: udp://127.0.0.1:514
        tag: "quality-display"
