#
# Configuration for the application 'data_quality'
#
name: "Data Quality"
slug: "data_quality"
version: "0.0.1"
description: "Can create data quality representations for the frontend"
url: ""

commands:
  - name: "dummy_refinement_quality_display"
    implemented_as: "python_callable"  # other options: "python_callable"
    parameters:
      - name: "input_cif_path"
        type: "QCrBox.input_cif"
        required_entries: [
          "_refine_ls.r_factor_all",
          "_refine_ls.goodness_of_fit_ref",
          "_refine_ls.d_res_high",
          "_refine_diff_density_max",
          "_refine_diff_density_min",
          "_refine_ls.wr_factor_gt"
        ]
        merge_su: False
  - name: "diederichs_2d_plot"
    implemented_as: "python_callable"  # other options: "python_callable"
    parameters:
      - name: "input_cif_path"
        type: "QCrBox.input_cif"
        required_entries: [
          "_diffrn_refln.intensity_net",
          "_diffrn_refln.intensity_net_su",
        ]
        merge_su: False
    doi: "10.1107/S0907444910014836"

qcrbox_yaml_spec_version: "0.1"