#
# Configuration for the application 'cod_check'
#
name: "COD Check"
slug: "cod_check"
version: "0.0.1"
description: "A tool to check and merge Crystallography Open Database (COD) entries into CIF files."
url: "https://my.official.module.url"

commands:
  - name: "merge_closest_cod_entry"
    implemented_as: "python_callable"
    import_path: "configure_cod_check"
    description: "Search the Crystallography Open Database (COD) for entries matching the structure in the input CIF file and merge the closest matching entry into the CIF file. If no matching entry is found, the input CIF file is returned unchanged."
    parameters:
      - name: "input_cif"
        description: "Path to the input CIF file."
        dtype: "QCrBox.cif_data_file"
        required_entries: [
          "_cell_length_a", "_cell_length_b", "_cell_length_c",
          "_cell_angle_alpha", "_cell_angle_beta", "_cell_angle_gamma",
          "_chemical_formula_sum"
        ]
        default_value: None
      - name: "output_cif_name"
        description: "Name of the the output CIF file."
        dtype: "QCrBox.output_cif"
        required_entries: [
          "_atom_site_label", "_atom_site_fract_x", "_atom_site_fract_y", "_atom_site_fract_z",
          "_atom_site_occupancy", "_atom_site_U_iso_or_equiv", "_atom_site_type_symbol",
          one_of: ["_symmetry_equiv_pos_as_xyz", "_space_group_symop_operation_xyz"]
        ]
        optional_entries: [
          "_atom_site_aniso_label", "_atom_site_aniso_U_11", "_atom_site_aniso_U_22",
          "_atom_site_aniso_U_33", "_atom_site_aniso_U_12", "_atom_site_aniso_U_13",
          "_atom_site_aniso_U_23", "_atom_site_adp_type", "_atom_site_site_symmetry_order",
          "_atom_site_calc_flag", "_atom_site_refinement_flags_posn", "_atom_site_refinement_flags_adp"
        ]
        invalidated_entries: [
          "_atom_site.*", "_geom.*", ".*refine.*", "_iucr.*", "_shelx.*"
        ]
      - name: "cellpar_deviation_perc"
        description: "The percentage deviation allowed for the unit cell parameters for the structure to still be considered a match."
        dtype: "float"
        default_value: 2.0
      - name: "listed_elements_only"
        description: "If True, only the elements listed in the chemical formula within the CIF file can be present, otherwise given elements must be present but additional elements are possible."
        dtype: "bool"
        default_value: false

cif_entry_sets:
  - name: "cell_elements"
    required: [
      "_cell_length_a", "_cell_length_b", "_cell_length_c", "_cell_angle_alpha",
      "_cell_angle_beta", "_cell_angle_gamma", "_chemical_formula_sum"
    ]

qcrbox_yaml_spec_version: "0.1"
