services:
  dummy_gui:
    image: "qcrbox/dummy_gui:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}"
    build:
      context: services/applications/dummy_gui/
      args:
        QCRBOX_DOCKER_TAG: ${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}
    depends_on:
      qcrbox-registry:
        condition: service_healthy
    networks:
      - qcrbox-net
    restart: unless-stopped
    environment:
      QCRBOX_APPLICATION_DISPLAY_NAME: "Dummy GUI"
      QCRBOX__NATS__HOST: "qcrbox-nats"
      QCRBOX__REGISTRY__SERVER__HOST: "qcrbox-registry"
      QCRBOX__REGISTRY__SERVER__PORT: "8000"
    labels:
      traefik.enable: true
      traefik.http.routers.to-dummy-gui-path-prefix.rule: Path(`/gui/dummy-gui`)
      traefik.http.routers.to-dummy-gui-path-prefix.middlewares: authelia-auth,redirect-gui-dummy-gui-path
      traefik.http.routers.to-dummy-gui-path-prefix.service: dummy-gui-service
      traefik.http.routers.to-dummy-gui-path-prefix.entrypoints: websecure
      traefik.http.middlewares.redirect-gui-dummy-gui-path.redirectregex.regex: ^https://(.+)/gui/dummy-gui(/?)$$
      traefik.http.middlewares.redirect-gui-dummy-gui-path.redirectregex.replacement: https://dummy-gui.gui.$$1/vnc.html?path=vnc&autoconnect=true&resize=remote&reconnect=true&show_dot=true

      traefik.http.routers.to-dummy-gui-subdomain.rule: Host(`dummy-gui.gui.${QCRBOX_DOMAIN:-qcrbox.localhost}`)
      traefik.http.routers.to-dummy-gui-subdomain.middlewares: authelia-auth,redirect-gui-dummy-gui-subdomain
      traefik.http.routers.to-dummy-gui-subdomain.service: dummy-gui-service
      traefik.http.routers.to-dummy-gui-subdomain.entrypoints: websecure
      traefik.http.middlewares.redirect-gui-dummy-gui-subdomain.redirectregex.regex: ^https://dummy-gui\.gui\.([^/]+)(/?)$$
      traefik.http.middlewares.redirect-gui-dummy-gui-subdomain.redirectregex.replacement: https://dummy-gui.gui.$$1/vnc.html?path=vnc&autoconnect=true&resize=remote&reconnect=true&show_dot=true

      traefik.http.services.dummy-gui-service.loadbalancer.server.scheme: http
      traefik.http.services.dummy-gui-service.loadbalancer.server.port: 8080

    logging:
      driver: "syslog"
      options:
        syslog-address: udp://127.0.0.1:514
        tag: "dummy_gui"
