#
# Configuration for the application 'qcrboxtools'
#
name: "QCrBoxTools"
slug: "qcrboxtools"
version: "0.0.5"
description: "Collection of tools that work with cif files"
url: "https://github.com/QCrBox/QCrBoxTools"

commands:
  - name: "replace_structure_from_cif"
    description: "Replace the structure (atoms/ADPs) in a CIF file with the structure from another CIF file."
    implemented_as: "python_callable"
    import_path: "configure_qcrboxtools"
    parameters:
      - name: "input_cif"
        dtype: "QCrBox.cif_data_file"
        default_value: None
        description: "Path to the CIF file where the structure should be replaced"
        required_entries: [
          "_space_group.crystal_system",
          one_of: ["_space_group.centring_type", "_space_group.name_h-m_alt", "_space_group.name_hall"]
        ]
        merge_su: No
      - name: "structure_cif"
        dtype: "QCrBox.data_file"
        default_value: None
        description: "CIF file containing the structure to be used for replacing the structure in the input CIF file"
      - name: "output_cif_name"
        dtype: "QCrBox.output_cif"
        description: "Name of the output CIF file that is exported back into QCrBox."
        required_entry_sets: ["molecular_structure"]
        invalidated_entries: [
          "_geom.*", "_refln.*calc.*", "_shelx.*", "_iucr.refine_instructions_details",
          '_refine(?!_ls\.weighting|_ls\.extinction).+', "_atom_site_aniso.u_.._su",
          "_atom_site.*"
        ]

  - name: "iso2aniso"
    description: "Convert isotropic ADPs of non-hydrogen atoms in a CIF file to anisotropic ADPs."
    implemented_as: "python_callable"
    import_path: "configure_qcrboxtools"
    parameters:
      - name: "input_cif"
        dtype: "QCrBox.cif_data_file"
        description: "Path to the CIF file to be converted"
        required_entries: [
          "_cell.length_a", "_cell.length_b", "_cell.length_c", "_cell.angle_alpha",
          "_cell.angle_beta", "_cell.angle_gamma", "_atom_site.label", "_atom_site.type_symbol",
          "_atom_site.u_iso_or_equiv", "_atom_site.adp_type"
        ]
        optional_entries: [
          "_atom_site_aniso.label", "_atom_site_aniso.u_11", "_atom_site_aniso.u_22",
          "_atom_site_aniso.u_33", "_atom_site_aniso.u_12", "_atom_site_aniso.u_13",
          "_atom_site_aniso.u_23"
        ]
        merge_su: False
      - name: "output_cif_name"
        dtype: "QCrBox.output_cif"
        description: "Name to use for exporting the CIF file back to QCrBox after converting"
        required_entries: [
          "_atom_site_aniso.label", "_atom_site_aniso.u_11", "_atom_site_aniso.u_22",
          "_atom_site_aniso.u_33", "_atom_site_aniso.u_12", "_atom_site_aniso.u_13",
          "_atom_site_aniso.u_23"
        ]
        invalidated_entries: [
          "_refln.*calc.*", "_shelx.*", "_iucr.refine_instructions_details",
          '_refine(?!_ls\.weighting|_ls\.extinction)'
        ]
      - name: "select_elements"
        dtype: "str"
        default_value: ""
        description: "Comma-separated list of element symbols to select which atoms to convert. If no atoms are converted."

cif_entry_sets:
  - name: "molecular_structure"
    required: [
      "_atom_site.label",
      "_atom_site.type_symbol",
      "_atom_site.fract_x",
      "_atom_site.fract_y",
      "_atom_site.fract_z",
      "_atom_site.occupancy",
      "_atom_site.u_iso_or_equiv"
    ]
    optional: [
      "_atom_site_aniso.label",
      "_atom_site_aniso.u_11",
      "_atom_site_aniso.u_22",
      "_atom_site_aniso.u_33",
      "_atom_site_aniso.u_12",
      "_atom_site_aniso.u_13",
      "_atom_site_aniso.u_23",
      "_atom_site.adp_type",
      "_atom_site.refinement_flags_posn",
    ]
  - name: "comparison"
    required: [
      "_cell.length_a", "_cell.length_b", "_cell.length_c",
      "_cell.angle_alpha", "_cell.angle_beta", "_cell.angle_gamma",
      "_atom_site.label", "_atom_site.type_symbol",
      "_atom_site.fract_x", "_atom_site.fract_y", "_atom_site.fract_z",
      "_atom_site_aniso.label", "_atom_site_aniso.type_symbol",
      "_atom_site_aniso.u_11", "_atom_site_aniso.u_22", "_atom_site_aniso.u_33",
      "_atom_site_aniso.u_12", "_atom_site_aniso.u_13", "_atom_site_aniso.u_23"
    ]
    optional: [
      "_atom_site.fract_x_su", "_atom_site.fract_y_su", "_atom_site.fract_z_su",
      "_atom_site_aniso.u_11_su", "_atom_site_aniso.u_22_su", "_atom_site_aniso.u_33_su",
      "_atom_site_aniso.u_12_su", "_atom_site_aniso.u_13_su", "_atom_site_aniso.u_23_su"
    ]

qcrbox_yaml_spec_version: "0.1"
