#
# Configuration for the application 'qcrboxtools'
#
name: "QCrBoxTools"
slug: "qcrboxtools"
version: "0.0.5"
description: "Collection of tools that work with cif files"
url: "https://github.com/QCrBox/QCrBoxTools"

commands:
  - name: "replace_structure_from_cif"
    implemented_as: "CLI"  # other options: "python_callable"
    parameters:
      - name: "input_cif_path"
        type: "QCrBox.input_cif"
        default_value: None
      - name: "structure_cif_path"
        type: "QCrBox.input_file" # not cif as it should not be cut to input_cif entries
        default_value: None
      - name: "output_cif_path"
        type: "QCrBox.output_cif"
        default_value: None
    input_cif:
      required_entries: [
        "_space_group.crystal_system",
        one_of: ["_space_group.centring_type", "_space_group.name_h-m_alt", "_space_group.name_hall"]
      ]
      merge_su: No
    output_cif:
      required_entry_sets: ["molecular_structure"]
      invalidated_entries: [
        "_geom.*", "_refln.*calc.*", "_shelx.*", "_iucr.refine_instructions_details",
        "_refine(?!_ls\.weighting|_ls\.extinction)"
      ]
      invalidated_entry_sets: ["molecular_structure"]
      merge_su: No

  - name: "check_structure_convergence"
    implemented_as: "CLI"  # other options: "python_callable"
    parameters:
      - name: "cif1_path"
        type: "QCrBox.input_cif"
        default_value: None
      - name: "cif2_path"
        type: "QCrBox.input_cif"
        default_value: None
      - name: "max_abs_position"
        type: "float"
        default_value: None
      - name: "max_position_su"
        type: "float"
        default_value: None
      - name: "max_abs_uij"
        type: "float"
        default_value: None
      - name: "max_uij_su"
        type: "float"
        default_value: None
      - name: "output_json_path"
        type: "QCrBox.output_file"
        default_value: None
    input_cif:
      required_entries: [
        "_cell.length_a", "_cell.length_b", "_cell.length_c", "_cell.angle_alpha",
        "_cell.angle_beta", "_cell.angle_gamma", "_atom_site.label", "_atom_site.type_symbol",
        "_atom_site.fract_x", "_atom_site.fract_y", "_atom_site.fract_z", "_atom_site_aniso.label",
        "_atom_site_aniso.type_symbol", "_atom_site_aniso.u_11", "_atom_site_aniso.u_22",
        "_atom_site_aniso.u_33", "_atom_site_aniso.u_12", "_atom_site_aniso.u_13",
        "_atom_site_aniso.u_23"
      ]
      merge_su: True

  - name: "iso2aniso"
    implemented_as: "CLI"  # other options: "python_callable"
    parameters:
      - name: "input_cif_path"
        type: "QCrBox.input_cif"
        default_value: null
      - name: "output_cif_path"
        type: "QCrBox.output_cif"
        default_value: null
      - name: "select_names"
        type: str
        default_value: null
        required: False
      - name: "select_elements"
        type: str
        default_value: null
        required: False
      - name: "select_regexes"
        type: str
        default_value: null
        required: False
    input_cif:
      required_entries: [
        "_cell.length_a", "_cell.length_b", "_cell.length_c", "_cell.angle_alpha",
        "_cell.angle_beta", "_cell.angle_gamma", "_atom_site.label", "_atom_site.u_iso_or_equiv"
      ]
      merge_su: False
    output_cif:
      required_entries: [
        "_atom_site_aniso.label", "_atom_site_aniso.u_11", "_atom_site_aniso.u_22",
        "_atom_site_aniso.u_33", "_atom_site_aniso.u_12", "_atom_site_aniso.u_13",
        "_atom_site_aniso.u_23"
      ]

  - name: "to_unified_cif"
    implemented_as: "CLI"  # other options: "python_callable"
    parameters:
      - name: "input_cif_path"
        type: "QCrBox.input_cif"
        default_value: None
      - name: "output_cif_path"
        type: "QCrBox.output_cif"
        default_value: None
      - name: "custom_category_list"
        type: "str"
        default_value: None
        required: False
    input_cif:
      optional_entries: ["all_unified"]
      merge_su: False
    output_cif:
      optional_entries: ["all_unified"]


cif_entry_sets:
  - name: "molecular_structure"
    required: [
      "_atom_site.label",
      "_atom_site.type_symbol",
      "_atom_site.fract_x",
      "_atom_site.fract_y",
      "_atom_site.fract_z"
      "_atom_site.occupancy",
      "_atom_site.u_iso_or_equiv"
    ]
    optional: [
      "_atom_site_aniso.label",
      "_atom_site_aniso.u_11",
      "_atom_site_aniso.u_22",
      "_atom_site_aniso.u_33",
      "_atom_site_aniso.u_12",
      "_atom_site_aniso.u_13",
      "_atom_site_aniso.u_23",
      "_atom_site.adp_type",
      "_atom_site.refinement_flags_posn",
    ]