services:
  olex2:
    image: ${QCRBOX_DOCKER_REPO:?Must set env var QCRBOX_DOCKER_REPO}/olex2-linux:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}
    networks:
      - qcrbox-net
    depends_on:
      qcrbox-registry:
        condition: service_healthy
    restart: unless-stopped
    environment:
      QCRBOX_APPLICATION_DISPLAY_NAME: "Olex2"
      QCRBOX__NATS__HOST: "qcrbox-nats"
      QCRBOX__REGISTRY__SERVER__HOST: "qcrbox-registry"
      QCRBOX__REGISTRY__SERVER__PORT: "8000"
    labels:
      traefik.enable: true
      traefik.http.routers.to-olex2-path-prefix.rule: Path(`/gui/olex2`)
      traefik.http.routers.to-olex2-path-prefix.middlewares: authelia-auth,redirect-gui-olex2-path
      traefik.http.routers.to-olex2-path-prefix.service: olex2-service
      traefik.http.routers.to-olex2-path-prefix.entrypoints: websecure
      traefik.http.middlewares.redirect-gui-olex2-path.redirectregex.regex: ^https://(.+)/gui/olex2(/?)$$
      traefik.http.middlewares.redirect-gui-olex2-path.redirectregex.replacement: https://olex2.gui.$$1/vnc.html?path=vnc&autoconnect=true&resize=remote&reconnect=true&show_dot=true

      traefik.http.routers.to-olex2-subdomain.rule: Host(`olex2.gui.${QCRBOX_DOMAIN:-qcrbox.localhost}`)
      traefik.http.routers.to-olex2-subdomain.middlewares: authelia-auth,redirect-gui-olex2-subdomain
      traefik.http.routers.to-olex2-subdomain.service: olex2-service
      traefik.http.routers.to-olex2-subdomain.entrypoints: websecure
      traefik.http.middlewares.redirect-gui-olex2-subdomain.redirectregex.regex: ^https://olex2\.gui\.([^/]+)(/?)$$
      traefik.http.middlewares.redirect-gui-olex2-subdomain.redirectregex.replacement: https://olex2.gui.$$1/vnc.html?path=vnc&autoconnect=true&resize=remote&reconnect=true&show_dot=true

      traefik.http.services.olex2-service.loadbalancer.server.scheme: http
      traefik.http.services.olex2-service.loadbalancer.server.port: 8080
    logging:
      driver: "syslog"
      options:
        syslog-address: udp://127.0.0.1:514
        tag: "olex2-linux"
