#
# Configuration for the application '{{ cookiecutter.application_slug }}'
#
name: "{{ cookiecutter.application_name }}"
slug: "{{ cookiecutter.application_slug }}"
version: "{{ cookiecutter.application_version }}"
description: "{{ cookiecutter.description }}"
url: "{{ cookiecutter.url }}"

commands:
  - name: "greet_and_sleep"
    description: "Print a greeting message, then wait for a given duration before returning."
    implemented_as: "python_callable"
    import_path: "pyqcrbox.helpers"
    parameters:
      - name: "name"
        dtype: str
        description: "The name to print"
      - name: "duration"
        dtype: float
        default_value: 5.0
        description: "Sleep duration (in seconds)"
        valid_value:
          numeric_range: [0, 10]

{%- if cookiecutter.application_type in ["Interactive GUI (Linux)", "Interactive GUI (Windows)"] %}
  - name: "interactive_session"
    implemented_as: "interactive_session"
    description: "Start dummy GUI in interactive mode"
    parameters:
      - name: "greeting"
        dtype: "str"
        description: "Message to display in the Dummy GUI after start-up"
    interactive_lifecycle:
      run:
        implemented_as: "cli_command"
        description: "Run command to launch the dummy GUI"
        call_pattern: "python dummy_gui.py {greeting}"
        used_basecommand_parameters: ["greeting"]
{%- endif %}

cif_entry_sets:
  - name: "example_entry_set"
    required: ["_cif_category.another_ddlm_entry"]
    optional: ["_cif_category.another_ddl1_entry"]

qcrbox_yaml_spec_version: "0.1"
