services:
  {{ cookiecutter.application_slug }}:
    image: "${QCRBOX_DOCKER_REPO:?Must set env var QCRBOX_DOCKER_REPO}/{{ cookiecutter.application_slug }}:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}"
    environment:
      QCRBOX_APPLICATION_DISPLAY_NAME: "{{ cookiecutter.application_name }}"
      QCRBOX__NATS__HOST: "qcrbox-nats"
      QCRBOX__REGISTRY__SERVER__HOST: "qcrbox-registry"
      QCRBOX__REGISTRY__SERVER__PORT: "8000"
    depends_on:
      qcrbox-registry:
        condition: service_healthy
    networks:
      - qcrbox-net
    restart: unless-stopped
    {%- if cookiecutter.application_type in ["Interactive GUI (Linux)", "Interactive GUI (Windows)"] %}
    labels:
      traefik.enable: true
      traefik.http.routers.to-{{cookiecutter.application_slug}}-path-prefix.rule: Path(`/gui/{{ cookiecutter.application_slug }}`)
      traefik.http.routers.to-{{cookiecutter.application_slug}}-path-prefix.middlewares: authelia-auth,redirect-gui-{{ cookiecutter.application_slug }}-path
      traefik.http.routers.to-{{cookiecutter.application_slug}}-path-prefix.service: {{ cookiecutter.application_slug }}-service
      traefik.http.routers.to-{{cookiecutter.application_slug}}-path-prefix.entrypoints: websecure
      traefik.http.middlewares.redirect-gui-{{cookiecutter.application_slug}}-path.redirectregex.regex: ^https://(.+)/gui/{{ cookiecutter.application_slug }}(/?)$$
      traefik.http.middlewares.redirect-gui-{{cookiecutter.application_slug}}-path.redirectregex.replacement: https://{{ cookiecutter.application_slug }}.gui.$$1/vnc.html?path=vnc&autoconnect=true&resize=remote&reconnect=true&show_dot=true

      traefik.http.routers.to-{{cookiecutter.application_slug}}-subdomain.rule: Host(`{{ cookiecutter.application_slug }}.gui.${QCRBOX_DOMAIN:-qcrbox.localhost}`)
      traefik.http.routers.to-{{cookiecutter.application_slug}}-subdomain.middlewares: authelia-auth,redirect-gui-{{ cookiecutter.application_slug }}-subdomain
      traefik.http.routers.to-{{cookiecutter.application_slug}}-subdomain.service: {{ cookiecutter.application_slug }}-service
      traefik.http.routers.to-{{cookiecutter.application_slug}}-subdomain.entrypoints: websecure
      traefik.http.middlewares.redirect-gui-{{cookiecutter.application_slug}}-subdomain.redirectregex.regex: ^https://{{ cookiecutter.application_slug }}\.gui\.([^/]+)(/?)$$
      traefik.http.middlewares.redirect-gui-{{cookiecutter.application_slug}}-subdomain.redirectregex.replacement: https://{{ cookiecutter.application_slug }}.gui.$$1/vnc.html?path=vnc&autoconnect=true&resize=remote&reconnect=true&show_dot=true

      traefik.http.services.{{ cookiecutter.application_slug }}-service.loadbalancer.server.scheme: http
      traefik.http.services.{{ cookiecutter.application_slug }}-service.loadbalancer.server.port: 8080
    {%- endif %}
    logging:
      driver: "syslog"
      options:
        syslog-address: udp://127.0.0.1:514
        tag: {{ cookiecutter.application_slug }}
