#
# Configuration for the application 'eval1x'
#
name: "Eval14/15"
slug: "eval1x"
version: "20231113"
description: "Eval14 and eval15 are integration methods for single crystal X-ray diffraction on area detectors. Both methods use knowledge about the exact experimental setup."
url: "http://www.crystal.chem.uu.nl/distr/eval/"

commands:
  - name: "interactive"
    implemented_as: "GUI"  # other options: "python_callable"
    parameters:
      - name: "work_folder"
        type: "str"
        default_value: None

  - name: "interactive"
    implemented_as: "python_callable"  # other options: "python_callable"
    parameters:
      - name: "work_folder"
        type: "str"
        default_value: None
      - name: "rmat_file_path"
        type: "str"
        default_value: None
      - name: "beamstop_file_path"
        type: "str"
        default_value: None
      - name: "detalign_file_path"
        type: "str"
        default_value: None
      - name: "maximum_res"
        type: "float"
        default_value: None
      - name: "minimum_res"
        type: "float"
        default_value: None
      - name: "box_size"
        type: "float"
        default_value: None
      - name: "box_depth"
        type: "int"
        default_value: None
      - name: "maximum_duration"
        type: "float"
        default_value: None
      - name: "min_refln_in_box"
        type: "int"
        default_value: None
      - name: "pic_dir"
        type: "str"
        default_value: None