#############################################################################
# Default syslog-ng.conf file which collects all local logs into a
# single file called /var/log/messages tailored to container usage.

@version: 4.2
@include "scl.conf"

#############################################################################
# Log messages sent to syslog container to a global file containing everything,
# qcrbox-log and qcrbox-structured and log each container to their own file too

source s_network_tcp {
  syslog(transport(tcp) port(601));
};

source s_network_udp {
  syslog(transport(udp) port(514));
};

destination d_all_logs {
  file("/var/log/qcrbox-log.log");
};

destination d_structured {
  file("/var/log/qcrbox-structured.log"
       template("$ISODATE $HOST $(format-welf --scope all-nv-pairs)\n")
       frac-digits(3));
};

destination d_program_logs {
  file("/var/log/${PROGRAM}.${HOST}.log");
};

log {
  source(s_network_tcp);
  source(s_network_udp);
  destination(d_all_logs);
};

log {
  source(s_network_tcp);
  source(s_network_udp);
  destination(d_structured);
};

log {
  source(s_network_tcp);
  source(s_network_udp);
  destination(d_program_logs);
};

#############################################################################
# Log internal events

source s_local {
  internal();
};

destination d_local {
    file("/var/log/internal.log");
};

log {
    source(s_local);
    destination(d_local);
};
