#
# Configuration for the application 'tonto_lamagoet'
#
name: "Tonto"
slug: "tonto_lamagoet"
version: "0.0.1"
description: "Tonto is the original software for Hirshfeld atom refinement and wavefunction fitting analyses"
url: "https://github.com/dylan-jayatilaka/tonto"

commands:
  - name: "run_hirshfeld"
    implemented_as: "python_callable"
    import_path: "configure_tonto_lamagoet"
    callable_name: "run_hirshfeld"
    parameters:
      - name: "input_cif_path"
        type: "QCrBox.input_cif"
        required_entry_sets: ["cell_data", "diffraction_data", "atom_data"]
      - name: "output_cif_path"
        type: "QCrBox.output_cif"
        required_entry_sets: ["atom_data"]
        invalidated_entries: ["_refine_.*", "_computing_.*", "_geom_.*"]

cif_entry_sets:
  - name: "cell_data"
    required : [
      "_space_group_IT_number",
      "_space_group_symop_id",
      "_space_group_symop_operation_xyz",
      "_cell_length_a",
      "_cell_length_b",
      "_cell_length_c",
      "_cell_angle_alpha",
      "_cell_angle_beta",
      "_cell_angle_gamma",
      "_cell_measurement_temperature"
    ]
  - name: "diffraction_data"
    required : [
      "_diffrn_radiation_type",
      "_diffrn_radiation_wavelength",
      "_diffrn_refln_index_h",
      "_diffrn_refln_index_k",
      "_diffrn_refln_index_l",
      "_diffrn_refln_intensity_net",
      "_diffrn_refln_intensity_u"
    ]
    optional : [
      "_chemical_formula_moiety",
      "_chemical_formula_sum",
      "_shelx_hkl_file"
    ]
  - name: "atom_data"
    required : [
      "_atom_site_label",
      "_atom_site_type_symbol",
      "_atom_site_fract_x",
      "_atom_site_fract_y",
      "_atom_site_fract_z",
      "_atom_site_U_iso_or_equiv",
      "_atom_site_adp_type",
      "_atom_site_occupancy"
    ]
    optional : [
      "_atom_type_symbol",
      "_atom_type_scat_dispersion_real",
      "_atom_type_scat_dispersion_imag",
      "_atom_type_scat_dispersion_source",
      "_space_group_crystal_system",
      "_atom_site_refinement_flags_posn",
      "_atom_site_aniso_label",
      "_atom_site_aniso_U_11",
      "_atom_site_aniso_U_22",
      "_atom_site_aniso_U_33",
      "_atom_site_aniso_U_12",
      "_atom_site_aniso_U_13",
      "_atom_site_aniso_U_23",
      "_iucr_refine_instructions_details",
      "_shelx_res_file"
    ]

qcrbox_yaml_spec_version: "0.1"