services:
  crystal-explorer:
    image: "${QCRBOX_DOCKER_REPO:?Must set env var QCRBOX_DOCKER_REPO}/crystal-explorer:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}"
    networks:
      - qcrbox-net
    depends_on:
      qcrbox-registry:
        condition: service_healthy
    restart: unless-stopped
    environment:
      QCRBOX_APPLICATION_DISPLAY_NAME: "CrystalExplorer"
      QCRBOX__NATS__HOST: "qcrbox-nats"
      QCRBOX__REGISTRY__SERVER__HOST: "qcrbox-registry"
      QCRBOX__REGISTRY__SERVER__PORT: "8000"
    labels:
      traefik.enable: true
      traefik.http.routers.to-crystal-explorer-path-prefix.rule: Path(`/gui/crystal-explorer`)
      traefik.http.routers.to-crystal-explorer-path-prefix.middlewares: authelia-auth,redirect-gui-crystal-explorer-path
      traefik.http.routers.to-crystal-explorer-path-prefix.service: crystal-explorer-service
      traefik.http.routers.to-crystal-explorer-path-prefix.entrypoints: websecure
      traefik.http.middlewares.redirect-gui-crystal-explorer-path.redirectregex.regex: ^https://(.+)/gui/crystal-explorer(/?)$$
      traefik.http.middlewares.redirect-gui-crystal-explorer-path.redirectregex.replacement: https://crystal-explorer.gui.$$1/vnc.html?path=vnc&autoconnect=true&resize=remote&reconnect=true&show_dot=true

      traefik.http.routers.to-crystal-explorer-subdomain.rule: Host(`crystal-explorer.gui.${QCRBOX_DOMAIN:-qcrbox.localhost}`)
      traefik.http.routers.to-crystal-explorer-subdomain.middlewares: authelia-auth,redirect-gui-crystal-explorer-subdomain
      traefik.http.routers.to-crystal-explorer-subdomain.service: crystal-explorer-service
      traefik.http.routers.to-crystal-explorer-subdomain.entrypoints: websecure
      traefik.http.middlewares.redirect-gui-crystal-explorer-subdomain.redirectregex.regex: ^https://crystal-explorer\.gui\.([^/]+)(/?)$$
      traefik.http.middlewares.redirect-gui-crystal-explorer-subdomain.redirectregex.replacement: https://crystal-explorer.gui.$$1/vnc.html?path=vnc&autoconnect=true&resize=remote&reconnect=true&show_dot=true

      traefik.http.services.crystal-explorer-service.loadbalancer.server.scheme: http
      traefik.http.services.crystal-explorer-service.loadbalancer.server.port: 8080
    logging:
      driver: "syslog"
      options:
        syslog-address: udp://127.0.0.1:514
        tag: "crystal-explorer"
