services:
  shelx:
    image: "qcrbox/shelx:${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}"
    build:
      context: services/applications/shelx/
      args:
        QCRBOX_DOCKER_TAG: ${QCRBOX_DOCKER_TAG:?Must set env var QCRBOX_DOCKER_TAG}
    environment:
      QCRBOX_REGISTRY_HOST: "qcrbox-registry"
      QCRBOX_REGISTRY_PORT: "8000"
    depends_on:
      qcrbox-registry:
        condition: service_healthy
    networks:
      - qcrbox-net
    restart: unless-stopped
