#
# Configuration for the application '{{ cookiecutter.application_slug }}'
#
name: "{{ cookiecutter.application_name }}"
slug: "{{ cookiecutter.application_slug }}"
version: "{{ cookiecutter.application_version }}"
description: "{{ cookiecutter.description }}"
url: "{{ cookiecutter.url }}"

commands:
  - name: "sample_cmd"
    implemented_as: "cli_command"
    description: "Sample command"
    call_pattern: /bin/bash /opt/{{ cookiecutter.application_slug }}/bin/sample_cmd.sh {input_cif_path} {output_cif_path}
    parameters:
      - name: "input_cif_path"
        dtype: "QCrBox.input_cif"
        decription: "Input CIF file"
        required_entries: ["_cif_category.ddlm_entry"]
        optional_entries: ["_cif_category_ddl1_entry"]
        required_entry_sets: ["example_entry_set"]
      - name: "output_cif_path"
        dtype: "QCrBox.output_cif"
        decription: "Output CIF file"
        required_entries: ["_cif_category.ddlm_entry"]
        optional_entries: ["_cif_category_ddl1_entry"]
        required_entry_sets: ["example_entry_set"]
        invalidated_entries: ["_processing_category\..*"]

  - name: "sample_cmd_v2"
    implemented_as: "python_callable"
    description: "Sample command v2"
    import_path: "configure_{{ cookiecutter.application_slug }}"
    callable_name: "needed_as_function_name_not_sample_cmd_v2"
    parameters:
      - name: "input_cif_path"
        dtype: "QCrBox.input_cif"
        decription: "Input CIF file"
        required_entries: ["_cif_category.ddlm_entry"]
        optional_entries: ["_cif_category_ddl1_entry"]
        required_entry_sets: ["example_entry_set"]
      - name: "output_cif_path"
        dtype: "QCrBox.output_cif"
        decription: "Output CIF file"
        required_entries: ["_cif_category.ddlm_entry"]
        optional_entries: ["_cif_category_ddl1_entry"]
        required_entry_sets: ["example_entry_set"]
        invalidated_entries: ["_processing_category\..*"]
      - name: "msg"
        dtype: str
        description: "A meaningful representation, accessible for non-experts"
        default_value: null
      - name: "some_number"
        dtype: int
        description: "Another meaningful representation, accessible for non-experts"
        default_value: 42
        required: False

cif_entry_sets:
  - name: "example_entry_set"
    required: ["_cif_category.another_ddlm_entry"]
    optional: ["_cif_category.another_ddl1_entry"]

qcrbox_yaml_spec_version: "0.1"
