#
# Configuration for the application 'crysalis-pro'
#
name: "CrysalisPro"
slug: "crysalis-pro"
version: "171.43.48a"
description: "CrysalisPro is used for data reduction on frame folders produced by Rigaku instruments."
url: "https://www.rigaku.com/de/products/smc/crysalis"

commands:
  - name: "interactive"
    implemented_as: "interactive"  # other options: "python_callable"
    description: "Run CrysalisPro interactively"
    parameters:
      - name: "par_path"
        type: "QCrBox.input_file"
        default_value: None
        description: "Path to the CrysAlisPro .par file. Must be located in the folder containing the remaining frames and other data"
      - name: "output_cif_path"
        type: "QCrBox.output_file"
        default_value: None
        description: "Path to save the CIF file to, after finishing the interactive session"
    interactive_lifecycle:
      run:
        implemented_as: "CLI"
        command: "wine /opt/wine_installations/wine_win64/drive_c/Xcalibur/CrysAlisPro171.43.48a/pro.exe {work_folder}"
        used_basecommand_parameters: ["work_folder"]
      finalise:
        implemented_as: "python_callable"
        module: "configure_crysalis-pro"
        function: "finalise__interactive"
        used_basecommand_parameters: ["work_folder", "output_cif_path"]

