name: "QCrBox CI"

# Controls when the workflow will run
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      # Checks out the  repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies

      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt

      - name: Build the documentation
        run: mkdocs build

      - name: Upload docs build output
        uses: actions/upload-artifact@v2
        with:
          name: qcrbox-docs
          path: ./build/docs_site/
