name: "QCrBox CI"

# Controls when the workflow will run
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_docs:
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      # Checks out the  repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: |
          pip install --upgrade uv
          uv pip install --system -r ./qcrbox/requirements-docs.txt
          uv pip install --system qcrbox@./qcrbox

      - name: Configure Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build and deploy with mike 🚀
        run: mike deploy --push ${{ steps.extract_branch.outputs.branch }}

#      - name: Create .tar.gz archive containing the docs build
#        run: cd .build/docs_site/ && tar -czvf ../qcrbox_docs.tar.gz .
#
#      - name: Upload docs build output as GitHub pages artifact
#        uses: actions/upload-pages-artifact@v2
#        with:
#          path: .build/docs_site/

#  deploy_docs:
#    needs: build_docs
#
#    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
#    permissions:
#      pages: write      # to deploy to Pages
#      id-token: write   # to verify the deployment originates from an appropriate source
#
#    # Deploy to the github-pages environment
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
#
#    # Specify runner and deployment step
#    runs-on: ubuntu-latest
#    steps:
#      - name: Configure GitHub Pages
#        uses: actions/configure-pages@v3
#
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print ruff version
        uses: chartboost/ruff-action@v1
        with:
          args: --version
      - uses: chartboost/ruff-action@v1
        with:
          args: check --config qcrbox/pyproject.toml
      - uses: chartboost/ruff-action@v1
        with:
          args: format --diff --config qcrbox/pyproject.toml
